#[repr(C)]
pub struct AomFirstpass {
    frame: f64,
    weight: f64,
    intra_error: f64,
    frame_avg_wavelet_energy: f64,
    coded_error: f64,
    sr_coded_error: f64,
    tr_coded_error: f64,
    pcnt_inter: f64,
    pcnt_motion: f64,
    pcnt_second_ref: f64,
    pcnt_third_ref: f64,
    pcnt_neutral: f64,
    intra_skip_pct: f64,
    inactive_zone_rows: f64,
    inactive_zone_cols: f64,
    MVr: f64,
    mvr_abs: f64,
    MVc: f64,
    mvc_abs: f64,
    MVrv: f64,
    MVcv: f64,
    mv_in_out_count: f64,
    new_mv_count: f64,
    duration: f64,
    count: f64,
    raw_error_stdev: f64,
    is_flash: i64,
    noise_var: f64,
    cor_coeff: f64
}