name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: docker build . --file Dockerfile --tag cogman/sav1n:$(date +%s) cogman/sav1n:latest
    - name: Docker login
      env:
        DOCKER_USER: cogman
        DOCKER_PASSWORD: ${{secrets.DOCKER_ACCESS_TOKEN}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Docker publish
      run: docker push -a cogman/sav1n
